
[[constraint]]
  branch = "master"
  name = "github.com/soh335/sliceflag"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "github.com/Knetic/govaluate"
